# Generated by Django 3.2 on 2021-05-12 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210508_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='blog.comment'),
        ),
    ]
