# Generated by Django 3.2 on 2021-05-12 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_parent_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags_Post',
            new_name='TagsPost',
        ),
    ]
