# Generated by Django 3.2 on 2021-05-12 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_tags_post_tagspost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagspost',
            options={'verbose_name': 'Tags Post', 'verbose_name_plural': 'Tags Posts'},
        ),
    ]
